;-------------------------------------------------------------------------
; Playfield data.
;-------------------------------------------------------------------------

pf0_data:       .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte $10
                .byte $30       ; 0
                .byte $F0       ;
                .byte $F0       ;
                .byte $F0       ;
                .byte $F0       ;
                .byte $F0       ;
                .byte $F0       ;
                .byte $B0       ;
                .byte $70       ; p
                .byte $F0       ;
                .byte $F0       ;
                .byte $F0       ;
                .byte $F0       ;
                .byte $F0       ;
                .byte $F0       ;
                .byte $F0       ;
                .byte $F0       ;
                .byte $70       ; p
                .byte $B0       ;
                .byte $F0       ;
                .byte $F0       ;
                .byte $70       ; p
                .byte $D0       ;
                .byte $90       ;
                .byte $90       ;
                .byte $80       ;
                .byte $80       ;
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte $10
                .byte $10
                .byte $30       ; 0
                .byte $30       ; 0
                .byte $70       ; p
                .byte $70       ; p
                .byte $E0       ;
                .byte $F0       ;
                .byte $B0       ;
                .byte $30       ; 0
                .byte $F0       ;
                .byte $70       ; p
                .byte $F0       ;
                .byte $F0       ;
                .byte $F0       ;
                .byte $F0       ;
                .byte $E0       ;
                .byte $B0       ;
                .byte $70       ; p
                .byte $D0       ;
                .byte $F0       ;
                .byte $70       ; p
                .byte $E0       ;
                .byte $C0       ;
                .byte 0
                .byte $80       ;
                .byte 0
pf1_data:       .byte 1
                .byte 3
                .byte 3
                .byte 7
                .byte $F
                .byte $F
                .byte $1E
                .byte $1F
                .byte $3F       ; ?
                .byte $3B       ; ;
                .byte $7D       ; }
                .byte $7E       ; ~
                .byte $E7       ;
                .byte $78       ; x
                .byte $37       ; 7
                .byte $3F       ; ?
                .byte $1E
                .byte $1D
                .byte $F
                .byte $F
                .byte 7
                .byte 5
                .byte 0
                .byte 0
                .byte $A0       ;
                .byte $E0       ;
                .byte $E0       ;
                .byte $F0       ;
                .byte $F0       ;
                .byte $B0       ;
                .byte $F8       ;
                .byte $F9       ;
                .byte $FF
                .byte $FF
                .byte $E7       ;
                .byte $FF
                .byte $7E       ; ~
                .byte $FE       ;
                .byte $DC       ;
                .byte $A8       ;
                .byte $FC       ;
                .byte $7C       ; |
                .byte $B4       ;
                .byte $EC       ;
                .byte $B8       ;
                .byte $B8       ;
                .byte $A8       ;
                .byte $88       ;
                .byte $20
                .byte $A8       ;
                .byte $A8       ;
                .byte $A8       ;
                .byte $A8       ;
                .byte $A8       ;
                .byte $88       ;
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte $18
                .byte $30       ; 0
                .byte $60       ; `
                .byte $E0       ;
                .byte $C3       ;
                .byte $C6       ;
                .byte $8F       ;
                .byte $DD       ;
                .byte $FF
                .byte $FF
                .byte $56       ; V
                .byte $FD       ;
                .byte $FF
                .byte $FF
                .byte $FE       ;
                .byte $DF       ;
                .byte $7D       ; }
                .byte $EF       ;
                .byte $F6       ;
                .byte $5B       ; [
                .byte $BF       ;
                .byte $FA       ;
                .byte $EC       ;
                .byte 0
pf2_data:       .byte $21; !
                .byte $63       ; c
                .byte $77       ; w
                .byte $7F       ;
                .byte $7F       ;
                .byte $7F       ;
                .byte $3F       ; ?
                .byte $BE       ;
                .byte $FD       ;
                .byte $7B       ; {
                .byte $37       ; 7
                .byte $29       ; )
                .byte $76       ; v
                .byte $7B       ; {
                .byte $7D       ; }
                .byte $7E       ; ~
                .byte $3F       ; ?
                .byte $3F       ; ?
                .byte $1F
                .byte $F
                .byte 7
                .byte 3
                .byte 1
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 4
                .byte $5E       ; ^
                .byte $FF
                .byte $FF
                .byte $FE       ;
                .byte $FE       ;
                .byte $EE       ;
                .byte $F6       ;
                .byte $FE       ;
                .byte $BC       ;
                .byte $FC       ;
                .byte $E8       ;
                .byte $E8       ;
                .byte $60       ; `
                .byte $60       ; `
                .byte $20
                .byte $20
                .byte 0
                .byte $20
                .byte $20
                .byte $20
                .byte $20
                .byte $20
                .byte $20
                .byte $20
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 1
                .byte 0
                .byte 1
                .byte 3
                .byte 1
                .byte 2
                .byte 3
                .byte 1
                .byte 1
                .byte 0
                .byte 1
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte 0
