;-------------------------------------------------------------------------
; Game logic, shared between platforms.
;-------------------------------------------------------------------------

;-------------------------------------------------------------------------

initial_addrs:  .byte VDELP1
                ; vertical delay player 1
                .byte COLUP0    ; colour-lum player 0
                .byte COLUP1    ; colour-lum player 1
                .byte pl_colours
                .byte pl_colours+1
                .byte byte_B8
                .byte byte_B7
                .byte unk_BD
                .byte unk_BD+1
                .byte pf0_data_ptr
                .byte pf0_data_ptr+1
                .byte pf1_data_ptr
                .byte pf1_data_ptr+1
                .byte pf2_data_ptr
                .byte pf2_data_ptr+1
                .byte p0_left_digit_ptr+1
                .byte p0_right_digit_ptr+1
                .byte p1_left_digit_ptr+1
                .byte p1_right_digit_ptr+1
                .byte enabl_data_ptr+1
                .byte grp0_data_ptr+1
                .byte grp1_data_ptr+1
                .byte pl_ys
                .byte pl_ys+1
                .byte pl_xs
                .byte pl_xs+1
                .byte byte_DB
                .byte byte_DB+1
                .byte pl_flags+1; b7 = player difficulty (0=pro 1=amateur)
initial_values: .byte 1
                ; VDELP1
                .byte 4         ; COLUP0
                .if PAL
                .byte $42       ; 2            ; COLUP1
                .else
                .byte $32       ; 2            ; COLUP1
                .endif
                .byte 6         ; p0_colour
                .if PAL
                .byte $46       ; 6            ; p1_colour
                .else
                .byte $36       ; 6            ; p1_colour
                .endif
                .byte $1A       ; b8
                .byte 7         ; b7
                .byte $A        ; bd
                .byte $A        ; be
                .word pf0_data  ; $92
                .word pf1_data  ; $94
                .word pf2_data  ; $96
                .byte $FB       ; p0_left_digit_ptr+1
                .byte $FB       ;             ; p0_right_digit_ptr+1
                .byte $FB       ;             ; p1_left_digit_ptr+1
                .byte $FB       ;             ; p1_right_digit_ptr+1
                .byte >sprite_row_selector_table ; enabl_data_ptr+1
                .byte >grp_data ;             ; grp0_data_ptr+1
                .byte >grp_data ;             ; grp1_data_ptr+1
                .byte 7         ; p0_y
                .byte 7         ; p1_y
                .byte $20
                .byte $6E       ; n
                .byte $B7       ;
                .byte $B7       ;
                .byte 8

;-------------------------------------------------------------------------

initialise_memory:.block
                ldy #28

loc_F21F:
                lda initial_values,y
                ldx initial_addrs,y
                sta 0,x
                dey
                bpl loc_F21F
                rts
                .endblock

;-------------------------------------------------------------------------

pl_state0_dxs:  .char 4, 2, 2, -2, -4, -6, 6, 6
pl_state0_dys:  .byte 4, 6, 6, 6, 4, 2, 2, 2
pl_state1a_dxs: .char 8, 4, 4, -4, -8, -$C, $C, $C
pl_state1a_dys: .byte 8, $C, $C, $C, 8, 4, 4, 4
pl_state1b_dxs: .char 11, 5, 5, -5, -11, -15, 15, 15
pl_state1b_dys: .byte 11, 15, 15, 15, 11, 5, 5, 5
                
byte_F25B:
                .byte 10
                .byte 13
                .byte 18
                .byte 128


                ; offsets of sprite ends
byte_F25F:
                .byte <(grp_frog3_end-1)
                .byte <(grp_frog2_end-1)
                .byte <(grp_frog1_end-1)
                .byte <(grp_frog0_end-1)

splash_frame_lsbs:
                .byte 0
                .byte 0
                .byte <(grp_splash0_end-1)
                .byte <(grp_splash0_end-1)
                .byte <(grp_splash0_end-1)
                .byte <(grp_splash0_end-1)
                .byte <(grp_splash1_end-1)
                .byte <(grp_splash1_end-1)
                .byte <(grp_splash1_end-1)
                .byte <(grp_splash1_end-1)
                .byte <(grp_splash2_end-1)
                .byte <(grp_splash2_end-1)
                .byte <(grp_splash2_end-1)
                .byte <(grp_splash2_end-1)
                .byte 0
                .byte 0
                .byte 0
                .byte 0
                .byte <(grp_splash3_end-1)
                .byte <(grp_splash3_end-1)
                .byte <(grp_splash3_end-1)
                .byte <(grp_splash3_end-1)
num_splash_frames=*-splash_frame_lsbs

;-------------------------------------------------------------------------

; Entry conditions for pl_state routines:
;
; A = player state routine MSB (probably not useful)
; X = player index
; Y = player state index
                
pl_state_routines=[pn_state0,pn_state1,pn_state2,pn_state3,pn_state4,pn_state5,pn_state6,pn_state7,pn_state8,pn_state9,pn_state10,pn_state11,pn_state12]

pl_state_routine_lsbs:.byte <pl_state_routines
pl_state_routine_msbs:.byte >pl_state_routines

;-------------------------------------------------------------------------

update_player_logic:.block
                lda byte_B3
                and #1
                tax
                ldy pl_states,x
                lda pl_state_routine_lsbs,y
                sta pn_state_routine_addr
                lda pl_state_routine_msbs,y
                sta pn_state_routine_addr+1
                jmp (pn_state_routine_addr)
                .endblock

;-------------------------------------------------------------------------

pn_state0:
                lda byte_B4
                bne loc_F320
                jsr initialise_player_difficulty
                jsr sub_F71F
                ldy p0_joystick_direction,x
                bmi loc_F304    ; taken if invalid direction
                lda pl_flags,x
                bmi loc_F2EF    ; taken if amateur difficulty
                and #pl_flags.is_moving
                beq loc_F2C8    ;taken if not moving
                cpy #JoystickDirection_Up
                beq loc_F2C7    ; taken if direction is Up
                cpy #JoystickDirection_Down
                bne loc_F2C8    ; taken if direction is not Down
; direction is D
                ldy #JoystickDirection_Left; translate D to L

loc_F2C7:
                iny             ; translate U to LU or L to LD

loc_F2C8:
                lda #1
                sta pl_states,x
                lda #27
                sta pl_counters,x
                sty unk_C9,x
                lda pl_state0_dxs,y
                sta pl_dxs,x
                lda pl_state0_dys,y
                sta pl_dys,x
                inc pl_ys,x
                lda pl_flags,x
                and #~pl_flags.is_moving
                cpy #JoystickDirection_Down
                bcs loc_F2EC    ; taken if Down, RightDown
                cpy #JoystickDirection_LeftUp
                bcc loc_F2EC    ; taken if Right, RightUp, Up
                ora #pl_flags.is_moving

loc_F2EC:
                sta pl_flags,x

locret_F2EE:
                rts

;-------------------------------------------------------------------------

loc_F2EF:
                lda pl_flags,x
                ldy #10
                and #pl_flags.is_moving
                beq loc_F2F9
                ldy #-10

loc_F2F9:
                sty pl_dxs,x
                lda #26
                sta pl_dys,x
                lda #7
                sta pl_states,x
                rts

;-------------------------------------------------------------------------

loc_F304:
                lda pl_flags,x
                and #$40
                beq locret_F2EE
                lda byte_B3
                and #$E
                bne locret_F2EE
                dec unk_BF,x
                bne locret_F2EE
                jsr rnd
                and #7
                clc
                adc #1
                sta unk_BF,x
                bpl loc_F2EF

loc_F320:
                lda pl_flags,x
                ora #pl_flags.tongue_out
                and #~pl_flags.is_moving
                ldy #20
                dex
                beq loc_F32F
                ora #8
                ldy #236

loc_F32F:
                sta pl_flags+1,x
                sty pl_dxs+1,x
                lda pl_xs+1,x
                inx
                beq loc_F33D
                lda #148
                sec
                sbc pl_xs,x

loc_F33D:
                lsr a
                lsr a
                lsr a
                lsr a
                tay
                lda byte_F35C,y
                sta pl_dys,x
                lda #6
                sta pl_states,x
                txa
                eor #1
                tay
                lda pl_states,y
                cmp #6
                bne locret_F2EE
                ldy #6
                jsr start_sound ; Y = sound
                                ; X = channel

locret_F35B:
                rts

;-------------------------------------------------------------------------

byte_F35C:      .byte 10
                .byte 11
                .byte 12
                .byte 13
                .byte 14
                .byte 15
                .byte 16
                .byte 17
                .byte 18

;-------------------------------------------------------------------------

pn_state6:
                lda pl_dxs,x
                beq loc_F37B
                lda pl_xs,x
                cmp #147
                bcs loc_F37B
                jsr sub_F51B
                lda byte_B3
                and #2
                bne locret_F35B
                dec pl_dys,x
                rts

;-------------------------------------------------------------------------

loc_F37B:
                lda #0
                sta pl_dys,x
                sta pl_ys,x
                txa
                eor #1
                tay
                lda pl_states,y
                cmp #6
                bne locret_F35B
                lda pl_ys,y
                bne locret_F35B
                lda #9
                sta pl_states
                lda #8
                sta pl_states+1
                rts

;-------------------------------------------------------------------------

pn_state8:
                rts

;-------------------------------------------------------------------------

pn_state9:
                lda mi_ys
                ora mi_ys+1
                bne locret_F35B
                lda #$A
                sta pl_states
                lda #$80
                sta byte_B4
                .if PAL
                lda #$2f
                .else
                lda #$FF
                .endif
                sta COLUP0      ; colour-lum player 0
                sta COLUP1      ; colour-lum player 1
                lda pl_flags  
                and #$F7
                sta pl_flags  
                lda #155
                sta mi_xs
                lda #56
                sta mi_ys
                lda #$FA
                sta mi_dxs
                lda #0
                sta mi_dys

locret_F3C5:
                rts

;-------------------------------------------------------------------------

pn_state10:     .block

                lda mi_xs
                cmp #$80
                bcs locret_F3C5
                lda #$B
                sta pl_states
                lda #138
                sta pl_xs
                lda #146
                sta pl_xs+1
                lda #60
                sta pl_ys
                sta pl_ys+1
                lda #250
                sta pl_dxs
                sta pl_dxs+1
                lda #147
                sta byte_DB
                lda #165
                sta byte_DB+1
                rts
                .endblock

;-------------------------------------------------------------------------

pn_state11:
                lda pl_xs
                cmp #72
                bcs locret_F3C5
                lda #12
                sta pl_states
                lda #0
                sta pl_dxs
                sta pl_dxs+1
                rts

;-------------------------------------------------------------------------

pn_state12:
                lda mi_dxs
                bne locret_F3C5
                lda #0
                sta mi_ys
                lda #8
                sta pl_states
                rts

;-------------------------------------------------------------------------

unk_F40B:       .byte $20
                .byte $2B
unk_F40D:       .byte $62
                .byte $6E

;-------------------------------------------------------------------------

pn_state7:
                jsr sub_F51B
                jsr clamp_player_x
                dec pl_dys,x
                lda pl_ys,x
                cmp #8
                bcs locret_F478
                lda #7
                sta pl_ys,x
                lda #0
                sta pl_states,x
                lda pl_flags,x
                eor #8
                sta pl_flags,x
                ldy unk_F40B,x
                and #8
                beq loc_F435
                ldy unk_F40D,x

loc_F435:
                sty pl_xs,x
                lda #$B7
                sta byte_DB,x
                lda #0
                sta pl_dxs,x
                sta pl_dys,x
                sta pl_tongue_counters,x
                rts

;-------------------------------------------------------------------------

pn_state1:
                jsr sub_F51B
                jsr clamp_player_x
                dec pl_counters,x
                beq loc_F474
                lda pl_counters,x
                ldy unk_C9,x
                cmp #23
                bne loc_F462
                lda pl_state1a_dxs,y
                sta pl_dxs,x
                lda pl_state1a_dys,y
                sta pl_dys,x
                bne loc_F470

loc_F462:
                cmp #19
                bne loc_F470
                lda pl_state1b_dxs,y
                sta pl_dxs,x
                lda pl_state1b_dys,y
                sta pl_dys,x

loc_F470:
                lda p0_joystick_direction,x
                bpl locret_F478

loc_F474:
                lda #2
                sta pl_states,x

locret_F478:
                rts

;-------------------------------------------------------------------------

pn_state2:
                jsr sub_F51B
                jsr clamp_player_x
                dec pl_dys,x
                lda pl_ys,x
                cmp #8
                bcs locret_F478
                lda #7
                sta pl_ys,x
                lda #0
                sta pl_states,x
                lda #$B7
                sta byte_DB,x
                lda #0
                sta pl_dxs,x
                sta pl_dys,x
                jsr is_on_lily  ; check if player is on lily
                                ; entry: X=player index
                                ; exit: C=1 if on lily, C=0 if not on lily
                bcs locret_F4B5
                lda #3
                sta pl_states,x
                lda pl_flags,x
                ora #2
                sta pl_flags,x
                lda #-12
                sta pl_dys,x
                lda #0
                sta pl_tongue_counters,x
                ldy #3
                jsr start_sound ; Y = sound
                                ; X = channel

locret_F4B5:
                rts

;-------------------------------------------------------------------------

pn_state3:
                lda pl_ys,x
                bne locret_F4B5
                sta pl_dys,x

                ; +1 to compensate for upcoming DEC
                lda #num_splash_frames+1
                sta pl_counters,x
                lda #4
                sta pl_states,x

pn_state4:
                dec pl_counters,x
                beq loc_F4D6    ; taken if splash done
                ldy pl_counters,x
                lda splash_frame_lsbs-1,y;byte_F25F+3,y
                beq loc_F4D3    ; taken if no sprite for this frame
                sta byte_DB,x
                lda #9

loc_F4D3:
                sta pl_ys,x
                rts

;-------------------------------------------------------------------------

loc_F4D6:
                lda #5
                sta pl_states,x
                lda #4
                sta pl_ys,x
                lda #$B7
                sta byte_DB,x
                lda pl_flags,x
                eor #8
                sta pl_flags,x
                ldy #4
                and #8
                beq loc_F4F0
                ldy #$FC

loc_F4F0:
                sty pl_dxs,x

locret_F4F2:
                rts

;-------------------------------------------------------------------------

pn_state5:; check if player is on lily
                jsr is_on_lily  ;
                                ; entry: X=player index
                                ; exit: C=1 if on lily, C=0 if not on lily
                bcc locret_F4F2
                lda #0
                sta pl_states,x
                lda pl_dxs,x
                rol pl_dxs,x
                ror a
                dex
                beq loc_F507
                rol pl_dxs+1,x
                ror a

loc_F507:
                inx
                adc pl_xs,x
                sta pl_xs,x
                lda #7
                sta pl_ys,x
                lda #0
                sta pl_dxs,x
                lda pl_flags,x
                and #$FD
                sta pl_flags,x
                rts

;-------------------------------------------------------------------------

sub_F51B:       .block
                lda pl_ys,x
                bmi locret_F530 ; taken if Y negative
                cmp #8
                bmi locret_F530 ; taken if Y<8
                ldy #$FF        ; Y=255

loc_F525:
                iny
                cmp byte_F25B,y
                bcs loc_F525
                lda byte_F25F,y
                sta byte_DB,x

locret_F530:
                rts
                .endblock

;-------------------------------------------------------------------------

clamp_player_x: .block
                lda pl_xs,x
                ldy #7
                cmp #7          ; minimum X
                bcc loc_F53F    ; taken if X<minimum - set X to minimum
                cmp #144        ; maximum X+1
                bcc locret_F545 ; taken if X<maximum - leave X unmodified
                ldy #143        ; maximum X

loc_F53F:
                sty pl_xs,x
                lda #0
                sta pl_dxs,x

locret_F545:
                rts
                .endblock

;-------------------------------------------------------------------------

; check if player is on lily
; entry: X=player index
; exit: C=1 if on lily, C=0 if not on lily

is_on_lily:     .block
                lda pl_xs,x
                cmp #13
                bcc clc_then_rts; taken if not on left lily
                cmp #68
                bcc sec_then_rts; taken if on left lily
                cmp #82
                bcc clc_then_rts; taken if not on right lily
                cmp #137
                bcc sec_then_rts; taken if on right lily

clc_then_rts:
                clc
                rts

;-------------------------------------------------------------------------

sec_then_rts:
                sec
                rts
                .endblock

;-------------------------------------------------------------------------

update_tongues: .block
                lda byte_B3
                and #1
                tax
                lda pl_tongue_counters,x
                beq loc_F568
                dec pl_tongue_counters,x
                rts

;-------------------------------------------------------------------------

loc_F568:
                lda pl_flags,x
                and #$C0
                beq loc_F59B
                ldy #1

loc_F570:
                lda pl_ys,x
                sec
                sbc mi_ys,y
                clc
                adc #1
                cmp #5
                bcs loc_F598
                lda mi_xs,y
                sbc pl_xs,x
                cmp #6
                bcc loc_F598
                pha
                lda pl_flags,x
                lsr a
                lsr a
                lsr a
                lsr a
                pla
                bcs loc_F594
                sbc #5
                eor #$FF

loc_F594:
                cmp #$F6
                bcs activate_tongue

loc_F598:
                dey
                beq loc_F570

loc_F59B:
                ldy pl_joystick_fire,x; Y=old fire state
                lda INPT4,x   ; read joystick fire button
                sta pl_joystick_fire,x; save state
                bmi locret_F5B3       ; taken if not pressed
                tya                   ; A=old fire state
                bpl locret_F5B3       ; taken if previously pressed

activate_tongue:
                lda pl_flags,x
                and #pl_flags.tongue_out
                bne locret_F5B3 ; taken if tongue already out?
                lda #8
                sta pl_tongue_counters,x
                jsr play_tongue_sound

locret_F5B3:
                rts
                .endblock

;-------------------------------------------------------------------------

update_player_physics:.block
                lda byte_DF
                clc
                adc #11
                and #15
                sta byte_DF
                ldx #3

loc_F5BF:
                lda pl_dxs,x
                clc
                adc byte_DF
                lsr a
                lsr a
                lsr a
                lsr a
                eor #8
                sec
                sbc #8
                clc
                adc pl_xs,x
                cmp #156
                bcs loc_F5D8
                sta pl_xs,x
                bcc loc_F5DC

loc_F5D8:
                lda #0
                sta pl_dxs,x

loc_F5DC:
                lda pl_dys,x
                clc
                adc byte_DF
                lsr a
                lsr a
                lsr a
                lsr a
                eor #8
                sec
                sbc #8
                clc
                adc pl_ys,x
                cmp #74
                bcs loc_F5F3
                sta pl_ys,x

loc_F5F3:
                dex
                bpl loc_F5BF
                rts
                .endblock

;-------------------------------------------------------------------------

byte_F5F7:      .byte $10
                .byte $20
byte_F5F9:      .byte $39
                .byte $31
byte_F5FB:      .byte $3F
                .byte $F

;-------------------------------------------------------------------------

sub_F5FD:       .block
                lda byte_B4
                bmi locret_F62A
                lda byte_B3
                lsr a
                lsr a
                lsr a
                and #1
                tax
                lda pl_flags  
                ora pl_flags+1
                asl a
                lda #0
                rol a
                tay
                lda mi_dxs,x
                bne loc_F62B
                lda mi_ys,x
                beq loc_F64A
                lda #0
                sta mi_ys,x
                sta mi_dys,x
                jsr rnd
                and #7
                clc
                adc #2
                sta unk_B9,x

locret_F62A:
                rts

;-------------------------------------------------------------------------

loc_F62B:
                lda mi_ys,x
                cmp byte_F5F7,y
                bcs loc_F636
                lda #0
                bpl loc_F63D

loc_F636:
                cmp byte_F5F9,y
                bcc loc_F64A
                lda #$80

loc_F63D:
                eor mi_dys,x
                bpl loc_F64A
                lda mi_dys,x
                eor #$FF
                sta mi_dys,x
                asl a
                ror mi_dys,x

loc_F64A:
                lda byte_B3
                and #7
                bne locret_F6BD
                dec unk_B9,x
                bpl locret_F6BD
                lda mi_ys,x
                bne loc_F688
                lda byte_B4
                bne locret_F6BD
                jsr rnd
                and #$F
                clc
                adc #6
                lsr a
                pha
                lda #0
                bcc loc_F670
                pla
                sbc #19
                pha
                lda #154

loc_F670:
                sta mi_xs,x
                pla
                sta mi_dxs,x

loc_F675:
                jsr rnd
                and byte_F5FB,y
                clc
                adc byte_F5F7,y
                cmp byte_F5F9,y
                bcs loc_F675
                sta mi_ys,x
                bne loc_F6A6

loc_F688:
                jsr rnd
                cmp #192
                php
                and #7
                clc
                adc #4
                plp
                ldy byte_B4
                beq loc_F699
                clc

loc_F699:
                ldy mi_dxs,x
                bmi loc_F6A0
                bcc loc_F6A4
                clc

loc_F6A0:
                bcs loc_F6A4
                eor #$FF

loc_F6A4:
                sta mi_dxs,x

loc_F6A6:
                jsr rnd
                tay
                and #$F
                sec
                sbc #8
                sta mi_dys,x
                tya
                lsr a
                lsr a
                lsr a
                lsr a
                and #7
                clc
                adc #8
                sta unk_B9,x

locret_F6BD:
                rts
                .endblock

;-------------------------------------------------------------------------

sub_F6BE:       .block
                ldy #0          ; Y=0 implies M0/PF collision
                lda CXM0FB ; A7 = collision M0/PF; A6 = collision M0/BL
                asl a              ; C=collision M0/PF; A7=collision M0/BL
                bmi any_collision  ; taken if M0/BL collision
                lda CXM1FB ; A7 = collision M1/PF; A6 = collision M1/BL
                asl a              ; C=collision M1/PF; A7=collision M1/BL
                bpl no_collision   ; taken if no M0/BL collision
                iny                ; Y=1 implies M1/BL collision

any_collision:
                tya             ; A: 0=M0/BL; 1=M1/BL
                eor byte_B3     ; handle dynamic user/PM index assignment????
                and #1          ; ensure just 0 or 1
                tay             ; Y=colliding player index
                ldx byte_E5
                lda mi_xs,y
                clc
                sbc pl_xs,x
                cmp #6
                bcc no_collision

                ; frog ate fly?
                jsr sub_FA6A

                ; score+=2
                lda pl_scores,x
                sed
                adc #2
                cld
                bcc loc_F6EA
                lda #$99        ; clamp score at 99
loc_F6EA:
                sta pl_scores,x
                ldx #0
                stx mi_dxs,y
                ldx #$50
                stx mi_ys,y

no_collision:
                rts
                .endblock

;-------------------------------------------------------------------------

initialise_player_difficulty:.block
                lda SWCHB       ; Console switches
                                ; +---+---+---+---+---+---+---+---+
                                ; |Di1|Di0|   |   |Col|   |~GS|~GR|
                                ; +-+-+-+-+---+---+-+-+---+-+-+-+-+
                                ;   |   |           |       |   |
                                ;   |   |           |       |   +--- 0 = game reset
                                ;   |   |           |       +------- 0 = game select
                                ;   |   |           +--------------- 0 = B&W, 1 = colour
                                ;   |   +--------------------------- 0 = P0 amateur, 1 = P0 pro
                                ;   +------------------------------- 0 = P1 amateur, 1 = P1 pro
                rol a           ; C=player 1 difficulty
                dex
                beq loc_F6FD    ; taken if X was 1 on entry
                rol a           ; C=player 0 difficulty

loc_F6FD:
                inx             ; restore X
                lda pl_flags,x
                bpl loc_F70B
                bcc locret_F708 ; taken if amateur difficulty
                and #$7F        ; mask off the pro bit
                sta pl_flags,x

locret_F708:
                rts

;-------------------------------------------------------------------------

initial_p_xs:   .byte 32
                .byte 110

;-------------------------------------------------------------------------

loc_F70B:
                bcs locret_F708
                ora #$80
                and #$F7
                dex
                bmi loc_F716
                ora #8

loc_F716:
                inx
                sta pl_flags,x
                lda initial_p_xs,x
                sta pl_xs,x
                rts
                .endblock

;-------------------------------------------------------------------------

sub_F71F:       .block
                lda byte_B3
                lsr a
                and #$1F
                bne locret_F747
                rol a
                tax
                dec unk_BD,x
                bne locret_F747
                lda pl_flags,x
                and #$40
                bne locret_F747
                ora #$40
                and #$F7
                dex
                bmi loc_F73B
                ora #8

loc_F73B:
                inx
                sta pl_flags,x
                lda initialise_player_difficulty.initial_p_xs,x
                sta pl_xs,x
                lda #2
                sta unk_BF,x

locret_F747:
                rts
                .endblock

;-------------------------------------------------------------------------

joystick_direction_by_inputs:
                .byte JoystickDirection_Invalid
                .byte JoystickDirection_Invalid
                .byte JoystickDirection_Invalid
                .byte JoystickDirection_Invalid
                .byte JoystickDirection_Invalid
                .byte JoystickDirection_RightDown
                .byte JoystickDirection_RightUp
                .byte JoystickDirection_Right
                .byte JoystickDirection_Invalid
                .byte JoystickDirection_LeftDown
                .byte JoystickDirection_LeftUp
                .byte JoystickDirection_Left
                .byte JoystickDirection_Invalid
                .byte JoystickDirection_Down
                .byte JoystickDirection_Up
                .byte JoystickDirection_Invalid

;-------------------------------------------------------------------------

handle_players_inputs:.block
                lda SWCHA       ; Joystick input:
                                ; +--+--+--+--+--+--+--+--+
                                ; |~R|~L|~D|~U|~R|~L|~D|~U|
                                ; +--+--+--+--+--+--+--+--+
                                ;  \----|----/ \----|----/
                                ;       P0          P1
                pha
                lsr a
                lsr a
                lsr a
                lsr a           ; A = P0 inputs
                ldx #0          ; X=0 - player 0
                jsr store_player_inputs
                pla
                and #$F         ; A = P1 inputs
                inx             ; X=1 - player 1
                .endblock

;-------------------------------------------------------------------------

store_player_inputs:.block
                cmp player_inputs,x
                sta player_inputs,x
                bne loc_F776
                tay
                lda joystick_direction_by_inputs,y
                sta p0_joystick_direction,x
                rts

;-------------------------------------------------------------------------

loc_F776:
                lda #$F
                sta unk_BD,x
                lda pl_flags,x
                and #~$40
                sta pl_flags,x
                rts
                .endblock

;-------------------------------------------------------------------------

rnd:            .block
                lda random_seed
                asl a
                asl a
                asl a
                asl a           ; seed<<4
                clc
                adc random_seed ; (seed<<4)+seed
                asl a
                asl a
                asl a           ; ((seed<<4)+seed)<<3
                clc
                adc random_seed ; (((seed<<4)+seed)<<3)+seed
                clc
                adc #149        ; (((seed<<4)+seed)<<3)+seed+149
                sta random_seed
                rts
                .endblock

;-------------------------------------------------------------------------

; frog X velocity table?
unk_F796:       .byte 4
                .byte 6
                .byte 8
                .byte 8
                .byte 8
                .byte 8
                .byte 6
                .byte 4

;-------------------------------------------------------------------------

; background colours?
unk_F79E:
                .if PAL

                .byte $54
                .byte $24
                .byte $56
                .byte $56

                .else

                .byte $C4       ; (0x40,0x7C,0x40)
                .byte $E4       ; (0x68,0x70,0x34)
                .byte $C6       ; (0x5C,0x9C,0x5C)
                .byte $C6       ; (0x5C,0x9C,0x5C)

                .endif
                
;-------------------------------------------------------------------------

unk_F7A2:
                .if PAL

                .byte $00
                .byte $00
                .byte $00
                .byte $d0
                .byte $b0
                .byte $b0
                .byte $b0
                .byte $d0
                .byte $b2
                .byte $b2
                .byte $b2
                .byte $d2
                .byte $b4
                .byte $b4
                .byte $b4
                .byte $d2
                .byte $b6
                .byte $b6
                .byte $b6
                .byte $d4
                .byte $b8
                .byte $b8
                .byte $b8
                .byte $d4
                .byte $ba
                .byte $ba
                .byte $ba
                .byte $d4
                
                .else
                
                .byte 0         ; (0x00,0x00,0x00)
                .byte 0         ; (0x00,0x00,0x00)
                .byte 0         ; (0x00,0x00,0x00)
                .byte $70       ; (0x14,0x00,0x84)
                .byte $90       ; (0x00,0x18,0x7C)
                .byte $90       ; (0x00,0x18,0x7C)
                .byte $90       ; (0x00,0x18,0x7C)
                .byte $70       ; (0x14,0x00,0x84)
                .byte $92       ; (0x1C,0x38,0x90)
                .byte $92       ; (0x1C,0x38,0x90)
                .byte $92       ; (0x1C,0x38,0x90)
                .byte $72       ; (0x30,0x20,0x98)
                .byte $94       ; (0x38,0x54,0xA8)
                .byte $94       ; (0x38,0x54,0xA8)
                .byte $94       ; (0x38,0x54,0xA8)
                .byte $72       ; (0x30,0x20,0x98)
                .byte $96       ; (0x50,0x70,0xBC)
                .byte $96       ; (0x50,0x70,0xBC)
                .byte $96       ; (0x50,0x70,0xBC)
                .byte $74       ; (0x4C,0x3C,0xAC)
                .byte $98       ; (0x68,0x88,0xCC)
                .byte $98       ; (0x68,0x88,0xCC)
                .byte $98       ; (0x68,0x88,0xCC)
                .byte $74       ; (0x4C,0x3C,0xAC)
                .byte $9A       ; (0x7C,0x9C,0xDC)
                .byte $9A       ; (0x7C,0x9C,0xDC)
                .byte $9A       ; (0x7C,0x9C,0xDC)
                .byte $74       ; (0x4C,0x3C,0xAC)

                .endif
;-------------------------------------------------------------------------

;-------------------------------------------------------------------------

                .if TARGET==TARGET_2600
                .include "tia_prepare_display.s65"
                .endif

;-------------------------------------------------------------------------

p0_colours:
                .byte 4
                .byte 6
                .byte 6
                .byte 2
                .byte 2
                .byte 4

p1_colours:
                .if PAL
                .byte $42
                .byte $42
                .byte $44
                .byte $40
                .byte $42
                .byte $44
                .else
                .byte $32
                .byte $32
                .byte $34
                .byte $30
                .byte $32
                .byte $34
                .endif

;-------------------------------------------------------------------------

sub_F8F0:       .block
                lda byte_B3
                and #$3F
                bne locret_F913
                dec byte_B8
                bne locret_F913
                lda #26
                sta byte_B8
                dec byte_B7
                beq loc_F90F
                ldx byte_B7
                lda p0_colours-1,x
                sta pl_colours
                lda p1_colours-1,x
                sta pl_colours+1
                rts

;-------------------------------------------------------------------------

loc_F90F:
                inc byte_B7
                inc byte_B4

locret_F913:
                rts
                .endblock
